name: multiple commands 

on: push

jobs:
  commands:
    runs-on: ubuntu-latest

    steps:
      - name: show date
        run: date

      - name: show current folder 
        run: pwd
     
      - name: show files
        run: ls -la